#include "define.h"
#include "html.h"

#include "cycle.h"
#include "display_text.h"
#include "light_random.h"
#include "rain.h"
#include "square_front_back.h"
#include "square_left_right.h"
#include "square_up_down.h"
#include "wave.h"
#include "dynamic.h"
#include "cube_expand.h"
#include "each_square.h"
#include "X_moving.h"
#include "mini_cube.h"
